
import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/navbar";
import Footer from "@/components/Footer";


export const metadata = {
  title: "vitrine-momo",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
